<template>
  <div>
    <header-content/>
    <section class="rootSection">
      <h1 class="title has-text-centered" id="">
        Polyhedron with Spherical Faces and<br> Three-dimensional Fractals
      </h1>
      <h2 class="subtitle is-8 has-text-centered" id="authors">
        Kento Nakamura and Kazushi Ahara
      </h2>
      <sectionContainer>
        <div slot="title">Introduction</div>
        <div slot="content">
          <div class="columns">
              <figure class="column has-text-centered contain">
                <img v-lazy="'../img/cube.png'"></img>
              </figure>
            <figure class="column has-text-centered contain">
              <img v-lazy="'../img/final.png'"></img>
            </figure>
          </div>
          <p class="no-indent">
            In this page, we show impressive three-dimensional fractal objects
            called <i>quasi-fuchsian fractals</i> or <i>quasi-spheres</i>.
            They are made by tiling of a <i>sphairahedron</i>, a polyhedron with spherical faces.
            Sphairahedron is a coined word combining two words sphaira-
            (a prefix that means ’spherical’) and -hedron (a suffix that means ’polyhedron.’)
            It is introduced by Kazushi Ahara and Yoshiaki Araki in 2003 [1] to invent a
            new kind of fractal objects.
          </p>
          <div class="columns has-text-centered">
            <figure class="column">
              <img v-lazy="'../img/sphairaTessellation.gif'" width="256px"></img><br>
              Tiling process of a finite sphairahedron
            </figure>
            <figure class="column">
              <img v-lazy="'../img/sphairaPrismTessellation.gif'" width="256px"></img><br>
              Tiling process of an infinite sphairahedron
            </figure>
          </div>
          <p class="no-indent">
            We can make a tiling pattern of sphairahedra using reflections through their faces.
            In many cases, the boundary of the tiling converges to a three-dimensional
            fractal shape as shown in Figure 2.
            The union of all the tiles is mostly homeomorphic to a three-dimensional ball.
            Thus this boundary is called a quasi-sphere.
            Mathematically speaking, we consider a Coxeter-like group generated by
            the inversions in all of the spherical faces of the sphairahedron,
            and we obtain the tiling after transforming the original sphairahedron by each
            element of the group.
            The boundary of the tiling is also called the limit set of the group.
            Also, under some technical conditions, the group is called a quasi-fuchsian group
            and the limit set a quasi-fuchsian fractal.
          </p>
          <figure class="has-text-centered padding">
            <iframe width="560" height="315"
                    src="https://www.youtube.com/embed/3lcO9zRCv-4?rel=0"
                    frameborder="0"
                    allow="autoplay; encrypted-media" allowfullscreen>
            </iframe>
          </figure>
          <p class="no-indent">
            A quasi-fuchsian fractals is one of the three-dimensional fractals at an early
            era of visualizing fractals with computer.
            The video posted by Ahara and Araki shows the fractal based on a cube type
            sphairahedron.
            Despite its interesting idea and impressive shape,
            there are few publications and computer graphics images.
            Thus, we show other types of sphairahedra and their fractals.
          </p>
        </div>
      </sectionContainer>
      <rendererContainer/>
      <galleryContainer/>
      <referenceContainer/>
    </section>
  </div>
</template>

<script>
import HeaderContent from './headerContent.vue';
import SectionContainer from './sectionContainer.vue';
import ReferenceContainer from './referenceContainer.vue';
import GalleryContainer from './galleryContainer.vue';
import RendererContainer from './rendererContainer.vue';

export default {
    components: {
        HeaderContent,
        SectionContainer,
        ReferenceContainer,
        GalleryContainer,
        RendererContainer,
    }
}
</script>

<style>
.rootSection{
    padding-right: 2rem;
    padding-left: 2rem;
}

p {
    text-indent: 1cm;
}

p.no-indent {
    text-indent: 0cm;
}

.padding {
    margin-top: 10px;
    margin-bottom: 10px;
}

#authors {
    margin-bottom: 0;
    margin-top: 1rem;
}

.contain {
    margin-left: 2rem;
    margin-right: 2rem;
}
         
</style>
